### PR TITLE
fix: delete socket file before run (fixed #1262)

### LINKED ISSUE #1262: docker版使用unix监听后无法重启容器
重启容器报错unix文件已存在

### PR DESCRIPTION
**Pull request by vvisionnn**

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -67,6 +68,16 @@ func main() {
 
 	// 如果启用了Unix
 	if conf.UnixConfig.Listen != "" {
+		// delete socket file before listening
+		if _, err := os.Stat(conf.UnixConfig.Listen); err == nil {
+			util.Log().Info("检测到 socket 文件已存在，删除中...")
```
Comment (HFO4) [inline main.go:73]: We can remove this line to make log less verbose, same as line 78

**Review by HFO4 — APPROVED** [review]

File: main.go (hunk 1 above)
Comment (vvisionnn) [reply main.go]: resolved in the latest update
